name: abstract_widget_view
description: A WidgetViewController pattern for seperatation of concerns
version: 0.0.2
# homepage:
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'  

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# flutter:

